"use client";

import { useState, useTransition } from "react";
import { deactivateBlogCategoryAction, saveBlogCategoryAction } from "@/lib/blog/actions";
import type { BlogLocale } from "@/lib/blog/constants";

type Category = { id: string; name: string; slug: string; description: string; locale: BlogLocale; seoTitle: string; seoDescription: string; isActive: boolean; posts: number };

export function CategoryManager({ locale, categories }: { locale: BlogLocale; categories: Category[] }) {
  const [message, setMessage] = useState<string | null>(null);
  const [isPending, startTransition] = useTransition();
  function submit(event: React.FormEvent<HTMLFormElement>, id?: string) { event.preventDefault(); const data = new FormData(event.currentTarget); if (id) data.set("id", id); startTransition(async () => { const result = await saveBlogCategoryAction(data); setMessage(result.ok ? result.message : result.error); if (result.ok) event.currentTarget.reset(); }); }
  return <div className="grid gap-6"><form onSubmit={(event) => submit(event)} className="premium-card grid gap-4 p-5 sm:p-6"><div><p className="eyebrow">New category</p><h2 className="mt-2 text-xl font-semibold text-primary">Add a focused topic</h2></div><div className="grid gap-4 md:grid-cols-3"><label className="form-label">Name<input className="form-input" name="name" required /></label><label className="form-label">Slug<input className="form-input" name="slug" pattern="[a-z0-9]+(?:-[a-z0-9]+)*" placeholder="digital-transformation" /></label><label className="form-label">Language<input type="hidden" name="locale" value={locale} /><input className="form-input" value={locale === "fr" ? "Français" : "English"} disabled /></label></div><label className="form-label">Description<textarea className="form-input min-h-24" name="description" /></label><div className="grid gap-4 md:grid-cols-2"><label className="form-label">SEO title<input className="form-input" name="seoTitle" maxLength={70} /></label><label className="form-label">SEO description<input className="form-input" name="seoDescription" maxLength={180} /></label></div><label className="flex items-center gap-2 text-sm text-muted"><input type="checkbox" name="isActive" defaultChecked />Active</label><button className="btn-primary justify-start" type="submit" disabled={isPending}>{isPending ? "Saving…" : "Create category"}</button>{message ? <p className="text-sm text-accent" role="status">{message}</p> : null}</form><div className="grid gap-4">{categories.map((category) => <CategoryRow key={category.id} category={category} onSubmit={submit} isPending={isPending} />)}</div></div>;
}

function CategoryRow({ category, onSubmit, isPending }: { category: Category; onSubmit: (event: React.FormEvent<HTMLFormElement>, id?: string) => void; isPending: boolean }) {
  const [editing, setEditing] = useState(false);
  const [status, setStatus] = useState("");
  if (!editing) return <div className="premium-card flex flex-wrap items-center justify-between gap-4 p-5"><div><p className="font-semibold text-primary">{category.name}</p><p className="mt-1 text-xs text-muted">/{category.slug} · {category.posts} articles · {category.isActive ? "Active" : "Inactive"}</p></div><div className="flex gap-2"><button type="button" className="btn-secondary" onClick={() => setEditing(true)}>Edit</button>{category.isActive ? <form action={async (formData: FormData) => { const result = await deactivateBlogCategoryAction(formData); setStatus(result.ok ? result.message : result.error); }}><input type="hidden" name="id" value={category.id} /><button className="btn-secondary" type="submit" disabled={isPending}>Deactivate</button></form> : null}</div>{status ? <p className="w-full text-xs text-accent">{status}</p> : null}</div>;
  return <form onSubmit={(event) => onSubmit(event, category.id)} className="premium-card grid gap-4 p-5 sm:p-6"><div className="flex items-center justify-between"><h3 className="font-semibold text-primary">Edit {category.name}</h3><button type="button" className="text-sm text-muted hover:text-primary" onClick={() => setEditing(false)}>Cancel</button></div><div className="grid gap-4 md:grid-cols-3"><label className="form-label">Name<input className="form-input" name="name" defaultValue={category.name} required /></label><label className="form-label">Slug<input className="form-input" name="slug" defaultValue={category.slug} required /></label><label className="form-label">Language<input type="hidden" name="locale" value={category.locale} /><input className="form-input" value={category.locale} disabled /></label></div><label className="form-label">Description<textarea className="form-input min-h-24" name="description" defaultValue={category.description || ""} /></label><div className="grid gap-4 md:grid-cols-2"><label className="form-label">SEO title<input className="form-input" name="seoTitle" defaultValue={category.seoTitle || ""} /></label><label className="form-label">SEO description<input className="form-input" name="seoDescription" defaultValue={category.seoDescription || ""} /></label></div><label className="flex items-center gap-2 text-sm text-muted"><input type="checkbox" name="isActive" defaultChecked={category.isActive} />Active</label><button className="btn-primary justify-start" type="submit" disabled={isPending}>Save category</button></form>;
}
